
version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./dbback:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3307:3307"

  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./dbback:/usr/local/apache2/htdocs
    depends_on:
      - php
